//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Master:public drogon::DrTemplate<Master>
{
public:
	Master(){};
	virtual ~Master(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
