//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Master.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
lude "Shared/Sidebar.csp"
using namespace drogon;
std::string Master::genText(const DrTemplateData& Master_view_data)
{
	drogon::OStringStream Master_tmp_stream;
	std::string layoutName{""};
	Master_tmp_stream << "    </div>\n";
	Master_tmp_stream << "    <div id=\"content\">\n";
	Master_tmp_stream << "        ";
{
    auto templ=DrTemplateBase::newTemplate("Content");
    if(templ){
      Master_tmp_stream<< templ->genText(Master_view_data);
    }
}
Master_tmp_stream<<"\n";
	Master_tmp_stream << "    </div>\n";
	Master_tmp_stream << "    <div id=\"footer\">\n";
	Master_tmp_stream << "        ";
{
    auto templ=DrTemplateBase::newTemplate("Footer");
    if(templ){
      Master_tmp_stream<< templ->genText(Master_view_data);
    }
}
Master_tmp_stream<<"\n";
	Master_tmp_stream << "    </div>\n";
	Master_tmp_stream << "</body>\n";
	Master_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(Master_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Master_view_data;
auto str = std::move(Master_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
